### ISSUE TITLE
Не используемая переменная 

### ISSUE THREAD

**Issue by saintbyte** [strizhechenko/tgbot-make-it-lists#1]
https://github.com/strizhechenko/tgbot-make-it-lists/blob/36a8dc850451b601554d2c50576ef56a517f6321/main.py#L6

Поставь уже линтер , black такое не пропустит

**Comment by strizhechenko** [comment]
Поставил три, не запустил ни один, собой доволен

**Comment by saintbyte** [comment]
Пре-коммит тебе надо ... ОСВ на тебя нет

**Comment by strizhechenko** [comment]
У меня есть, но per-project и только для работы, а не для хуйни на коленке за часик.

**Comment by saintbyte** [comment]
Это не ОСВ говорил что "нет более постоянного чем временное"? Вот тебе кажется что это хуйня на часик , а потом говнокодить и курить начнешь =)
